MERGE `ch_meteo.dwpnt_10min` t
USING (
  SELECT DISTINCT *
  FROM `ch_meteo.dwpnt_10min`
  WHERE DATE(date_time) = CURRENT_DATE()
)
ON FALSE
WHEN NOT MATCHED BY SOURCE AND DATE(date_time) = CURRENT_DATE() THEN DELETE
WHEN NOT MATCHED BY TARGET THEN INSERT ROW